-- V23__add_soft_delete_to_entities.sql

ALTER TABLE accommodation ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
ALTER TABLE discount_policy ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
ALTER TABLE event ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
ALTER TABLE member ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
ALTER TABLE payment ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
ALTER TABLE reservation ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
ALTER TABLE review ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
ALTER TABLE wishlist ADD COLUMN deleted_at DATETIME(6) DEFAULT NULL;
