-- V27__Insert_Amenities.sql

INSERT INTO amenity (name) VALUES
                               ('WIFI'),
                               ('AIR_CONDITIONER'),
                               ('HEATING'),
                               ('KITCHEN'),
                               ('WASHER'),
                               ('DRYER'),
                               ('PARKING'),
                               ('TV'),
                               ('HAIR_DRYER'),
                               ('IRON'),
                               ('SHAMPOO'),
                               ('BED_LINENS'),
                               ('EXTRA_PILLOWS'),
                               ('CRIB'),
                               ('HIGH_CHAIR'),
                               ('DISHWASHER'),
                               ('COFFEE_MACHINE'),
                               ('MICROWAVE'),
                               ('REFRIGERATOR'),
                               ('ELEVATOR'),
                               ('POOL'),
                               ('HOT_TUB'),
                               ('GYM'),
                               ('SMOKE_ALARM'),
                               ('CARBON_MONOXIDE_ALARM'),
                               ('FIRE_EXTINGUISHER'),
                               ('PETS_ALLOWED'),
                               ('OUTDOOR_SPACE'),
                               ('BBQ_GRILL'),
                               ('BALCONY'),
                               ('UNKNOWN');
