bootstrap.servers=kafka.lab.airbob.internal:9092
group.id=airbob-debezium-connect

config.storage.topic=airbob_debezium_configs
offset.storage.topic=airbob_debezium_offsets
status.storage.topic=airbob_debezium_statuses
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.storage.StringConverter

plugin.path=/opt/kafka/connect-plugins

rest.port=8083
rest.advertised.host.name=connect.lab.airbob.internal
rest.advertised.port=8083

offset.flush.interval.ms=10000

producer.bootstrap.servers=kafka.lab.airbob.internal:9092
consumer.bootstrap.servers=kafka.lab.airbob.internal:9092
